# -*- coding: utf-8 -*-
"""internintelligencetask.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/eliyevaulviye/4dfa39f0a73360ec3822681f73f8fc10/internintelligencetask.ipynb

# ***Importing libraries***
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from sklearn.preprocessing import StandardScaler, MinMaxScaler

"""***DATASET OVERVIEW***




"""

df = pd.read_csv('MentalHealthSurvey.csv')
df

#Number of rows and columns
df.shape

#Viewing first 10 rows
df.head(10)

#Displaying data types of each column
df.dtypes

#Description of the data
df.describe()

#Checking for missing values
df.isnull().sum()

"""## ***Data Cleaning***"""

#Filling missing numeric values with mean
df.fillna(df.mean(numeric_only=True),inplace=True)
df

#Removing duplicates
df.drop_duplicates()
df

#Handling outliers
z_scores = np.abs(stats.zscore(df.select_dtypes(include=[np.number])))
z_scores

#Removing outliers
df_no_outlier = df[(z_scores<3).all(axis=1)]
df_no_outlier

"""***Exploratory Data Analysis (EDA)***"""

#Gender vs Depression
plt.figure(figsize=(6, 4))
sns.boxplot(x='gender', y='depression', data=df, palette='Set1')
plt.title('Depression Levels by Gender')
plt.xlabel('Gender')
plt.ylabel('Depression')
plt.show()

# Distribution of academic pressure
plt.figure(figsize=(6, 4))
sns.histplot(df['academic_pressure'], bins=10, kde=True, color='purple')
plt.title('Distribution of Academic Pressure')
plt.xlabel('Academic Pressure')
plt.ylabel('Frequency')
plt.show()

#Spports Engagement by Gender
plt.figure(figsize=(8, 5))
sns.countplot(x='sports_engagement', hue='gender', data=df, palette='Set1')
plt.title('Sports Engagement by Gender')
plt.xlabel('Sports Engagement')
plt.ylabel('Count')
plt.show()

# Correlation matrix heatmap
plt.figure(figsize=(10, 8))
corr_matrix = df[['academic_pressure', 'depression', 'anxiety', 'isolation']].corr()
sns.heatmap(corr_matrix, annot=True, cmap='Blues', linewidths=0.5)
plt.title('Correlation Matrix of Mental Health Factors and Academic Pressure')
plt.show()